env:
  problem_cls: "TSPProblem"
  n_particles: 128 # Dummy value, not used in ACO
  step_per_epoch: 128

  # Problem specific settings
  n_cities: &n_cities 20
  k_sparse: 5

aco_agent:
  n_cities: *n_cities
  n_ants: 20
  mode: "choice" # "range" or "choice"
  aco_iterations_infer: 20


trainer:
  max_epochs: 5
  accelerator: "auto"
  devices: "auto"
  num_sanity_val_steps: 0
  log_every_n_steps: 16
  default_root_dir: "logs/aco_tsp"