# Settings for dataset, aka environment
env:
  # PSO env settings
  problem_cls: "TSPProblem"
  n_particles: 64

  # Problem general specific settings
  n_dims: 2
  eval_n_starts: 1
  init_n_heuristic: 0

  training_cfg:
    batch_size: 1
    n_cities: 20
    k_sparse: 5
    mode: "choice" # "range" or "choice"
    steps_per_epoch: 32
  
  validation_cfg:
    batch_size: 4
    n_cities: 20
    k_sparse: 5
    mode: "choice"
    random_include: False
    random_size: 100

rl_agent:
  name: "TSPAgent"
  args:
    emb_dim: 32
    act_fn: "silu"

rl_train:
  name: "PolicyGradientNaive"
  args:
    pso_iterations_train: 32
    pso_iterations_infer: 64

trainer:
  max_epochs: 10
  val_check_interval: 1.0
  accelerator: "auto"
  devices: "auto"
  num_sanity_val_steps: 0
  log_every_n_steps: 16
  